### ISSUE TITLE
Documentation Review

### ISSUE THREAD

**Issue by sfregosi** [sfregosi/agate#54]
Megan is kindly providing a thorough review of the website/documentation text and some testing of the documented examples as are available and possible (not piloting stuff as we don't have gliders in the water!) 

Tracking/feedback document is here: [Agate Documentation Review](https://docs.google.com/document/d/1-UdjjB6KJM-UB1gTE7cdMlK0_iNhtNF0672Fukiuzk0/edit#heading=h.qs72ziwcz7vm)

It seemed easier to add outline/add review feedback there, but also fine to add comments here if questions come up. I imagine some of the bigger comments will spur specific GH Issues.

**Comment by megwood2012** [comment]
@sfregosi Testing to see if I can comment/interact with this issue :)

**Comment by sfregosi** [comment]
@megwood2012 and @sfregosi met to go over initial feedback, generally small changes. All are outlined as tasks in the Google Doc. 

Decided to hold off on actually testing running the software until some additional changes are made (CONFIG not global?? #57) Will revisit in early June

**Comment by sfregosi** [comment]
implemented all edits from first review
